### ISSUE TITLE
The mixin is set to only work on singleplayer

### ISSUE THREAD

**Issue by DaveyL2013** [animeavi/TrampleDisablerFabric#1]
In the mixins.json, MixinFarmlandBlock is placed within the client section, so it will only work on singleplayer. I'm fairly certain it was put there by accident and was meant for the currently left empty mixins section instead to run on both singleplayer and on a server. 

For now if somebody is having issues running this on a server, you should just be able to open up the mod jar in your archive explorer of choice and open the "trampledisablerfabric.mixins.json" file, and then just swap the mixins and client section (The empty client section isn't even needed, so you could delete that if you want to save that precious less than a kilobyte of storage space).

**Comment by animeavi** [comment]
This was my first Fabric mod so I didn't do it on purpose, I just copied some example code and changed things around, I'll fix it.

**Comment by animeavi** [comment]
Should be fixed now, thanks for your report.
