### ISSUE TITLE
Does it work on 1.18.2?

### ISSUE THREAD

**Issue by Laifsyn** [animeavi/TrampleDisablerFabric#4]

**Comment by Scarlaid** [comment]
It doesn't, on servers, as far as I know
It does on singleplayer though

**Comment by animeavi** [comment]
Sorry for the delay
Should work now -> https://github.com/animeavi/TrampleDisablerFabric/releases/tag/v1.0.5
I'll work on getting it to work for 1.19 and posting to curseforge later today
